version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  cache:
    layerinfo: inmemory
  filesystem:
    rootdirectory: <%= node['registry_2']['storage']['directory'] %>
http:
  addr: localhost:5000
  <% if node['registry_2']['secret'] %>secret: <%= node['registry_2']['secret'] %><% end %>
  debug:
    addr: localhost:5001