FROM debian:wheezy

MAINTAINER "Alex Lispython"

RUN echo "deb http://httpredir.debian.org/debian wheezy-backports main" >> /etc/apt/sources.list

ENV NGINX_VERSION 1.6.2-5~bpo70+1

RUN apt-get update && apt-get install -y ca-certificates && apt-get -t wheezy-backports install -y nginx-extras=${NGINX_VERSION} && rm -rf /var/lib/apt/lists/*


RUN rm -rf /etc/nginx/conf.d/*
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/*
RUN mkdir /etc/nginx/auth

VOLUME ["/var/cache/nginx"]

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log


EXPOSE 80 443


CMD ["nginx", "-g", "daemon off;"]