FROM ubuntu:14.04


RUN apt-get update && apt-get install netcat-openbsd


EXPOSE 7777


#CMD ["nc", "-l", "-p 7777"]

CMD ["while true; do echo -e "HTTP/1.1 200 OK\n\n $(date)" | nc -l -p 7777; done"]

ENTRYPOINT ["/bin/bash"]